repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  - repo: https://github.com/dotnet/format
    rev: v5.1.250801
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet format
        language: system
        pass_filenames: false
        types_or: [c#]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        entry: hadolint
        language: docker_image
        types: [dockerfile]

  - repo: local
    hooks:
      - id: dotnet-test
        name: Run .NET tests
        entry: dotnet test
        language: system
        pass_filenames: false
        types_or: [c#]
        stages: [push]

      - id: check-secrets
        name: Check for secrets
        entry: bash -c 'grep -rE "(password|secret|key|token)\s*=\s*[\"'\''][^\"'\'']+[\"'\'']" --include="*.cs" --include="*.json" --include="*.yaml" --include="*.yml" --exclude-dir=bin --exclude-dir=obj . || true'
        language: system
        pass_filenames: false